[package]
name = "physics"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fixed = "1.23.1"
fixed-macro = "1.2.0"
fixed-sqrt = "0.2.5"
rand = "0.8.5"
raylib = "3.7.0"
rayon = "1.7.0"
